version: '3.8'

services:
  mcp-commerce-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__McpCommerceServer=Debug
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/mcp/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
